version: '3'

services:
  app:
    image: prisma-example:latest
    build: .
    env_file: .env
    environment:
      HOST: 0.0.0.0
      DATABASE_URL: "postgresql://postgres:newrelic@db/prisma"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15
    expose:
      - "5432"
    # Let's show the SQL queries, for illustrative purposes
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=newrelic
      - POSTGRES_DB=prisma
